USE FooddeliveryDB;

CREATE TABLE Area (
    AreaID INT PRIMARY KEY AUTO_INCREMENT,
    AreaName VARCHAR(100) NOT NULL,
    LatCoordinate DECIMAL(10,6) DEFAULT NULL,
    LngCoordinate DECIMAL(10,6) DEFAULT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE Rider (
    RiderID INT PRIMARY KEY AUTO_INCREMENT,
    PersonID INT NOT NULL,
    AssignedAreaID INT DEFAULT NULL,
    AdminID INT DEFAULT NULL,
    VehicleType VARCHAR(50) NOT NULL DEFAULT 'Bike',
    Licence VARCHAR(50) NOT NULL DEFAULT '',
    IsAvailable BOOLEAN NOT NULL DEFAULT TRUE,
    AvgRating DECIMAL(3,2) NOT NULL DEFAULT 0.00,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PersonID) REFERENCES Person(PersonID) ON DELETE CASCADE,
    FOREIGN KEY (AssignedAreaID) REFERENCES Area(AreaID) ON DELETE SET NULL,
    FOREIGN KEY (AdminID) REFERENCES Admin(AdminID) ON DELETE SET NULL,
    UNIQUE KEY uq_rider_person (PersonID)
) ENGINE=InnoDB;

CREATE TABLE Address (
    AddressID INT PRIMARY KEY AUTO_INCREMENT,
    CustomerID INT DEFAULT NULL,
    EmployeeID INT DEFAULT NULL,
    AreaID INT DEFAULT NULL,
    Label VARCHAR(50) NOT NULL DEFAULT 'Home',
    Street VARCHAR(100) NOT NULL DEFAULT '',
    City VARCHAR(50) NOT NULL DEFAULT '',
    Latitude DECIMAL(10,6) DEFAULT NULL,
    Longitude DECIMAL(10,6) DEFAULT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID) ON DELETE CASCADE,
    FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID) ON DELETE SET NULL,
    FOREIGN KEY (AreaID) REFERENCES Area(AreaID) ON DELETE SET NULL
) ENGINE=InnoDB;

ALTER TABLE Customer
    ADD CONSTRAINT fk_customer_default_address
    FOREIGN KEY (DefaultAddressID) REFERENCES Address(AddressID) ON DELETE SET NULL;
