USE FooddeliveryDB;

CREATE TABLE Restaurant (
    RestaurantID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Logo VARCHAR(200) NOT NULL DEFAULT '',
    OpenTime TIME NOT NULL DEFAULT '10:00:00',
    CloseTime TIME NOT NULL DEFAULT '23:00:00',
    BaseLocation VARCHAR(100) NOT NULL DEFAULT '',
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE Category (
    CategoryID INT PRIMARY KEY AUTO_INCREMENT,
    RestaurantID INT NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Description VARCHAR(200) NOT NULL DEFAULT '',
    DisplayOrder INT NOT NULL DEFAULT 1,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    ImgURL VARCHAR(255) NOT NULL DEFAULT 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    FOREIGN KEY (RestaurantID) REFERENCES Restaurant(RestaurantID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE MenuItem (
    MenuItemID INT PRIMARY KEY AUTO_INCREMENT,
    CategoryID INT NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Description VARCHAR(200) NOT NULL DEFAULT '',
    IsAvailable BOOLEAN NOT NULL DEFAULT TRUE,
    BasePrice DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ImgURL VARCHAR(255) NOT NULL DEFAULT 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80',
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE MenuItemVariant (
    VariantID INT PRIMARY KEY AUTO_INCREMENT,
    MenuItemID INT NOT NULL,
    Label VARCHAR(50) NOT NULL,
    PriceDelta DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (MenuItemID) REFERENCES MenuItem(MenuItemID) ON DELETE CASCADE
) ENGINE=InnoDB;
