USE FooddeliveryDB;

CREATE TABLE Person (
    PersonID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Phone VARCHAR(20) NOT NULL DEFAULT '',
    Password VARCHAR(255) NOT NULL,
    Role VARCHAR(20) NOT NULL DEFAULT 'Customer',
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_person_email (Email)
) ENGINE=InnoDB;

CREATE TABLE Customer (
    CustomerID INT PRIMARY KEY AUTO_INCREMENT,
    PersonID INT NOT NULL,
    WalletBalance DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    DefaultAddressID INT DEFAULT NULL,
    FOREIGN KEY (PersonID) REFERENCES Person(PersonID) ON DELETE CASCADE,
    UNIQUE KEY uq_customer_person (PersonID)
) ENGINE=InnoDB;

CREATE TABLE Admin (
    AdminID INT PRIMARY KEY AUTO_INCREMENT,
    PersonID INT NOT NULL,
    Permissions VARCHAR(200) NOT NULL DEFAULT '',
    LastLogin DATETIME DEFAULT NULL,
    FOREIGN KEY (PersonID) REFERENCES Person(PersonID) ON DELETE CASCADE,
    UNIQUE KEY uq_admin_person (PersonID)
) ENGINE=InnoDB;

CREATE TABLE Employee (
    EmployeeID INT PRIMARY KEY AUTO_INCREMENT,
    PersonID INT NOT NULL,
    AdminID INT DEFAULT NULL,
    JobTitle VARCHAR(50) NOT NULL DEFAULT '',
    Department VARCHAR(50) NOT NULL DEFAULT '',
    HireDate DATE DEFAULT NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (PersonID) REFERENCES Person(PersonID) ON DELETE CASCADE,
    FOREIGN KEY (AdminID) REFERENCES Admin(AdminID) ON DELETE SET NULL,
    UNIQUE KEY uq_employee_person (PersonID)
) ENGINE=InnoDB;
