USE FooddeliveryDB;

CREATE TABLE Review (
    ReviewID INT PRIMARY KEY AUTO_INCREMENT,
    OrderID INT NOT NULL,
    CustomerID INT NOT NULL,
    RiderID INT DEFAULT NULL,
    FoodRating TINYINT NOT NULL CHECK (FoodRating BETWEEN 1 AND 5),
    RiderRating TINYINT DEFAULT NULL CHECK (RiderRating BETWEEN 1 AND 5),
    Comment VARCHAR(200) NOT NULL DEFAULT '',
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE,
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID) ON DELETE CASCADE,
    FOREIGN KEY (RiderID) REFERENCES Rider(RiderID) ON DELETE SET NULL,
    UNIQUE KEY uq_review_order (OrderID)
) ENGINE=InnoDB;

CREATE TABLE Notification (
    NotificationID INT PRIMARY KEY AUTO_INCREMENT,
    PersonID INT NOT NULL,
    Title VARCHAR(100) NOT NULL,
    Message VARCHAR(200) NOT NULL DEFAULT '',
    Type VARCHAR(50) NOT NULL DEFAULT 'info',
    IsRead BOOLEAN NOT NULL DEFAULT FALSE,
    SentAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PersonID) REFERENCES Person(PersonID) ON DELETE CASCADE
) ENGINE=InnoDB;
